dataset.image_path: "~\\Documents\\data\\aml\\maskedSubset"
dataset.label_path: "~\\Documents\\data\\aml\\seg_mask128png"
dataset.preload_percentage: 1

train_loader.batch_size: 16
train_loader.shuffle: true
train_loader.num_workers: 8

val_loader.batch_size: 16
val_loader.shuffle: false
val_loader.num_workers: 8

training.max_epochs: 50
training.learning_rate: 0.001
training.break_criterion: 15
training.lr_scheduler.step_size: 10
training.lr_scheduler.gamma: 0.1
training.out_path: "."

model.in_channels: 3
model.channels_per_depth: [16, 32, 64, 128]
model.final_out_channels: 1