dataset.params.image_path: "~/Documents/data/aml/masked128png"
dataset.params.label_path: "~/Documents/data/aml/seg_mask128png"
dataset.params.preload_percentage: 0.011
dataset.train_label: "~/Documents/data/aml/train_dataset.json"
dataset.val_label: "~/Documents/data/aml/val_dataset.json"
dataset.test_label: "~/Documents/data/aml/test_dataset.json"
dataset.type: SegmentationDataset

train_loader.batch_size: 20
train_loader.shuffle: true
train_loader.num_workers: 0

val_loader.batch_size: 20
val_loader.shuffle: false
val_loader.num_workers: 0

training.max_epochs: 55
training.learning_rate: 0.001
training.break_criterion: 15
training.lr_scheduler.step_size: 7
training.lr_scheduler.gamma: 0.1
training.out_path: "./training_results"
training.iou_th: 0.002

model.params.in_channels: 3
model.params.channels_per_depth: [16, 32, 64, 128]
model.params.final_out_channels: 1
model.type: SegmentationTrainer